services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LOCAL_PATH}/portainer/data:/data
    ports:
      - 9000:9000
    depends_on:
      - pihole
    networks:
      - ron-net

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ALLOW_INTERNAL_REQUESTS=true
    volumes:
      - ${LOCAL_PATH}/heimdall:/config
    depends_on:
      - pihole
    networks:
      - ron-net

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    environment:
      - TZ=${TZ}
      - FTLCONF_webserver_api_password=${PIHOLE_PSW}
      - FTLCONF_dns_listeningMode=ALL
      - FTLCONF_dns_upstreams=1.1.1.1;1.0.0.1;8.8.8.8;8.8.4.4
    volumes:
      - ${LOCAL_PATH}/pihole:/etc/pihole
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    networks:
      - ron-net

  # https://docs.linuxserver.io/images/docker-jellyfin/
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    pull_policy: always
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHEDSERVERURL}
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - ${LOCAL_PATH}/jellyfin/config:/config
      - ${NAS_PATH}/tv_shows:/data/tvshows
      - ${NAS_PATH}/anime:/data/anime
      - ${NAS_PATH}/movies:/data/movies
    ports:
      - "8096:8096"
      - "7359:7359/udp"
    group_add:
      - "992"
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      - pihole
    networks:
      - ron-net

  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    pull_policy: always
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCAL_PATH}/prowlarr/data:/config
    ports:
      - "9696:9696"
    depends_on:
      - pihole
    networks:
      - ron-net

  # https://docs.linuxserver.io/images/docker-sonarr/
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    pull_policy: always
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCAL_PATH}/sonarr/data:/config
      - ${NAS_PATH}/tv_shows:/tv_shows
      - ${NAS_PATH}/anime:/anime
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - "8989:8989"
    depends_on:
      - pihole
    networks:
      - ron-net

  # https://github.com/MainKronos/Sonarr-AnimeDownloader
  sonarr_anime:
    image: ghcr.io/mainkronos/anime_downloader:latest
    container_name: sonarr_anime
    pull_policy: always
    restart: unless-stopped
    environment:
      - SONARR_URL=http://sonarr.ron.home
      - ANIMEWORLD_URL=https://www.animeworld.ac
      - API_KEY=${SONARR_APIKEY}
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${LOCAL_PATH}/sonarr_anime/data:/src/database
      - ${NAS_PATH}/anime:/anime
      - ${DOWNLOAD_PATH}/anime:/downloads
      - ${LOCAL_PATH}/sonarr_anime/connections:/src/script
    ports:
      - "5000:5000"
    depends_on:
      - pihole
    networks:
      - ron-net

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    pull_policy: always
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCAL_PATH}/radarr/data:/config
      - ${NAS_PATH}/movies:/movies
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - "7878:7878"
    depends_on:
      - pihole
    networks:
      - ron-net

  # https://docs.linuxserver.io/images/docker-bazarr/#usage
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    pull_policy: always
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCAL_PATH}/bazarr/config:/config
      - ${NAS_PATH}/movies:/movies
      - ${NAS_PATH}/tv_shows:/tv_shows
      - ${NAS_PATH}/anime:/anime
    ports:
      - 6767:6767
    depends_on:
      - pihole
    networks:
      - ron-net

  # https://docs.linuxserver.io/images/docker-qbittorrent/
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    pull_policy: always
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8088
      - TORRENTING_PORT=6881
    volumes:
      - ${LOCAL_PATH}/qbittorrent:/config
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - "8088:8088"
      - "6881:6881"
      - "6881:6881/udp"
    depends_on:
      - pihole
    networks:
      - ron-net

  nginx-proxy:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy
    pull_policy: always
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISABLE_IPV6=true
    volumes:
      - ${LOCAL_PATH}/nginx-proxy/data:/data
      - ${LOCAL_PATH}/nginx-proxy/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    depends_on:
      - pihole
    networks:
      - ron-net

networks:
  ron-net:
    driver: bridge
